name: "Common cmake steps"
description: "Encapsulate cmake composite run steps that are common for Windows, Linux and Mac"
# reference https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-composite-run-steps-action
inputs:
  conan-visual-version:
    description: "MSVC version: 16, 17 represent msvc-2019 and msvc-2022"
    required: true
  conan-visual-runtime:
    description: "MD or MDd"
    required: true
  conan-build-type:
    description: "Debug or Release"
    required: true
  vcpkg-artifactory-url:
    description: "pass secrets.VCPKG_ARTIFACTORY_URL"
    required: true
  vcpkg-artifactory-token:
    description: "pass secrets.VCPKG_ARTIFACTORY_TOKEN"
    required: true
  conan-pem:
    description: "pass secrets.LKEB_CERT_CHAIN"
    required: true
  rs_ssh_key:
    description: "pass secrets.RULESSUPPORT_DEPLOY_KEY"
    required: true
  sentry-upload:
    description: "Whether to upload program database (and associated) files to Sentry"
    required: true
  sentry-url:
    description: "pass secrets.LKEB_SENTRY_URL"
    required: true
  sentry-org:
    description: "pass secrets.LKEB_SENTRY_ORG"
    required: true
  sentry-project:
    description: "pass secrets.LKEB_SENTRY_PROJECT"
    required: true
  sentry-auth-token:
    description: "pass secrets.LKEB_SENTRY_AUTH_TOKEN"
    required: true
  sentry-root:
    description: "Sentry search root"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
      - name: Clone vcpkg
        uses: actions/checkout@v6
        with:
          repository: microsoft/vcpkg
          path: .vcpkg

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13' 

      - name: Enable Windows Long Paths
        if: runner.os == 'Windows'
        run: New-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force
        shell: pwsh

      - name: Bootstrap vcpkg and python
        shell: pwsh
        run: | 
          $vcpkgRoot = Join-Path "${{ github.workspace }}" ".vcpkg"
          echo "VCPKG_ROOT=$vcpkgRoot" >> $env:GITHUB_ENV
          if ($env:RUNNER_OS -eq "Windows") {
            & "${{ github.workspace }}\.vcpkg\bootstrap-vcpkg.bat" -disableMetrics
            $python = Join-Path $env:pythonLocation "python.exe"
          } else {
            & "${{ github.workspace }}\.vcpkg\bootstrap-vcpkg.sh" -disableMetrics
            $python = Join-Path $env:pythonLocation "bin" "python3"
          }
          Add-Content -Path $env:GITHUB_ENV -Value "PYTHON3_EXECUTABLE=$python"
          echo ${{ github.workspace }}\.vcpkg\ >> $GITHUB_PATH
          echo "VCPKG_FEATURE_FLAGS=registries" >> $env:GITHUB_ENV
          $config_path = Join-Path ${{ github.workspace }} test registry-tester vcpkg-configuration.json
          echo "VCPKG_CONFIG_FILE=$config-path" >> $env:GITHUB_ENV
          $test_workdir = Join-Path ${{ github.workspace }} test registry-tester
          Add-Content -Path $env:GITHUB_ENV -Value "TEST_WORKDIR=$test_workdir"

      - name: Install required Python packages
        shell: pwsh
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install requests packaging colorama

      - name: Install Linux build dependencies and add pem chain to cert store
        if: runner.os == 'Linux'
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build pkg-config
          sudo cp lkebartifactory.nl.crt /usr/local/share/ca-certificates/
          sudo update-ca-certificates                    

      - name: Configure project   # this drives the port build
        shell: pwsh
        env:
          VCPKG_KEEP_ENV_VARS: "PYTHON3_EXECUTABLE;SEVEN_ZIP_EXECUTABLE"
          VCPKG_BINARY_SOURCES: "clear;http,${{ inputs.vcpkg-artifactory-url }}/{name}/{version}/{triplet}/{sha},readwrite,Authorization: Bearer ${{ inputs.vcpkg-artifactory-token }}" 
          VCPKG_FEATURE_FLAGS: "versions,registries"
        run: |
          $preset = if ($IsWindows) { "vcpkg-windows" }
            elseif ($IsLinux) { "vcpkg-linux" }
            else { "vcpkg-macos" }
          $buildDir = Join-Path "." "build"
          vcpkg search hdilib --debug
          cmake --preset $preset -S . -B $buildDir 
   
      - name: Upload vcpkg install log on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: vcpkg-manifest-install-log
          path: | 
            D:/a/core/core/build/vcpkg-manifest-install.log


      - name: Build tester
        shell: pwsh
        env:
          VCPKG_FEATURE_FLAGS: "versions,registries"
        run: | 
          Set-Location "$env:TEST_WORKDIR"
          cmake --build .\build