name: "Matrix prepare"
description: "Supply a matrix GITHUB_OUTPUT"
inputs:
  matrix_name:
    description: 'The name of the matrix to be returned defaults to default.json'
    default: 'default.json'
    required: false

  combine:
    description: "A list of matrix name to be combined e.g. 'windows_2019.json linux_gcc11.json', takes precedence over matrix_name "
    default: ''
    required: false

outputs:
  matrix: 
    description: "The centrally defined matrix"
    value: ${{ steps.set-matrix.outputs.matrix }}

runs:
  using: "composite"
  steps:
  - name: Get common matrix  
    uses: actions/checkout@v4
    with:
      repository: ManiVaultStudio/github-actions
      ref: compatibility
      path: matrix
      fetch-depth: 1

  - name: Get matrix from file  
    run: |
        if [ -n "${{ inputs.combine }}" ]; then
          jfiles=''
          for jfile in "${{ inputs.combine }}"
          do
            jfiles="$jfiles matrix/build_matrices/$jfile"  
          done

          echo "matrix<<EOF" >> $GITHUB_OUTPUT
          echo "$(jq -s '[.[][]]' $jfiles)" >> $GITHUB_OUTPUT
          echo EOF >> $GITHUB_OUTPUT
        else
          echo "matrix<<EOF" >> $GITHUB_OUTPUT
          echo "$(cat matrix/build_matrices/${{ inputs.matrix_name }})" >> $GITHUB_OUTPUT
          echo EOF >> $GITHUB_OUTPUT 
        fi
    id: set-matrix 
    shell: bash

  - name: Log matrix
    run: |
      echo "Matrix content"
      echo "${{ steps.set-matrix.outputs.matrix }}"
    shell: bash