name: "Matrix prepare"
description: "Supply a matrix GITHUB_OUTPUT"
outputs:
  matrix: 
    description: "The centrally defined matrix"
    value: ${{ steps.set-matrix.outputs.matrix }}

runs:
  using: "composite"
  steps:
  - name: Get common matrix  
    uses: actions/checkout@v4
    with:
      repository: ManiVaultStudio/github-actions
      ref: compatibility
      path: matrix
      fetch-depth: 1

  - name: Get matrix from file  
    run: |
        echo "matrix<<EOF" >> $GITHUB_OUTPUT
        echo "$(cat matrix/matrix.json)" >> $GITHUB_OUTPUT
        echo EOF >> $GITHUB_OUTPUT 
    id: set-matrix 
    shell: bash