name: "Matrix prepare"
description: "Supply a matrix GITHUB_OUTPUT"
inputs:
  matrix_name:
    description: 'The name of the matrix to be returned defaults to default.json'
    default: 'default.json'
    required: false

outputs:
  matrix: 
    description: "The centrally defined matrix"
    value: ${{ steps.set-matrix.outputs.matrix }}

runs:
  using: "composite"
  steps:
  - name: Get common matrix  
    uses: actions/checkout@v4
    with:
      repository: ManiVaultStudio/github-actions
      ref: compatibility
      path: matrix
      fetch-depth: 1

  - name: Get matrix from file  
    run: |
        echo "matrix<<EOF" >> $GITHUB_OUTPUT
        echo "$(cat matrix/build_matrices/${{ inputs.matrix_name }})" >> $GITHUB_OUTPUT
        echo EOF >> $GITHUB_OUTPUT 
    id: set-matrix 
    shell: bash

  - name: Log matrix
    run: |
      echo "Matrix content"
      echo "${{ steps.set-matrix.outputs.matrix }}"
    shell: bash