name: "Matrix prepare"
description: "Supply a matrix GITHUB_OUTPUT"
inputs:
  matrix_ids:
    description: | 
      "A list of matrix ids to be used. Choose from

       - windows_2019 
       - linux_gcc11 
       - macos_code14 
       
       If empty the list 'windows_2019 linux_gcc11 macos_code14' is used"
    default: 'windows_2019 linux_gcc11 macos_code14'
    required: false

outputs:
  matrix: 
    description: "The centrally defined matrix"
    value: ${{ steps.set-matrix.outputs.matrix }}

runs:
  using: "composite"
  steps:
  - name: Get common matrix  
    uses: actions/checkout@v4
    with:
      repository: ManiVaultStudio/github-actions
      ref: compatibility
      path: matrix
      fetch-depth: 1

  - name: Get matrix from file  
    run: |
        if [ -n "${{ inputs.matrix_ids }}" ]; then
          all_files=""
          for jfile in ""${{ inputs.matrix_ids }}""; do all_files+=" matrix/build_matrices/$jfile.json"; done
          echo "matrix is composed of $all_files"
          echo "matrix<<EOF" >> $GITHUB_OUTPUT
          echo "$(jq -s '[.[][]]' $all_files)" >> $GITHUB_OUTPUT
          echo EOF >> $GITHUB_OUTPUT
        fi
    id: set-matrix 
    shell: bash

  - name: Log matrix
    run: |
      echo "Matrix content"
      echo "${{ steps.set-matrix.outputs.matrix }}"
    shell: bash