name: Upload matching PDBs (reusable)

on:
  workflow_call:
    inputs:
      search-root:
        description: Root to scan for binaries/PDBs
        required: false
        type: string
        default: D:/.conan/

jobs:
  upload:
    runs-on: windows-latest
    steps:
      - name: Install sentry-cli
        if: startsWith(github.ref, 'refs/heads/release/')
        shell: bash
        run: |
          set -euo pipefail
          curl -sSfL https://sentry.io/get-cli/ | bash
      
          # Add whichever install location exists to PATH for subsequent steps
          if [ -x "/usr/local/bin/sentry-cli" ]; then
            echo "/usr/local/bin" >> "$GITHUB_PATH"
          fi
          if [ -x "$HOME/.sentry-cli/bin/sentry-cli" ]; then
            echo "$HOME/.sentry-cli/bin" >> "$GITHUB_PATH"
          fi
          
      - name: Verify
        if: startsWith(github.ref, 'refs/heads/release/')
        shell: bash
        run: |
          which sentry-cli || true
          sentry-cli --version
  
      - name: Checkout the source
        if: startsWith(github.ref, 'refs/heads/release/')
        uses: actions/checkout@v4
        with:
          repository: ManiVaultStudio/github-actions
          ref: refs/heads/upload_pdbs
          
      - name: Show config (no secrets)
        if: startsWith(github.ref, 'refs/heads/release/')
        shell: bash
        run: |
          echo "Using URL=${SENTRY_URL:-<empty>}, ORG=${SENTRY_ORG:-<empty>}, PROJECT=${SENTRY_PROJECT:-<empty>}"
          echo "SEARCH_ROOT=${{ inputs.search-root }}"

      - name: Upload matching PDBs
        if: startsWith(github.ref, 'refs/heads/release/')
        shell: bash
        env:
          # Pull from repo/org variables or override via environment protection rules
          SENTRY_URL:     ${{ vars.SENTRY_URL }}     # e.g. https://sentry.io/
          SENTRY_ORG:     ${{ vars.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT }}
          
          # Secret comes from the caller via 'secrets: inherit'
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          bash "$GITHUB_WORKSPACE/sentry/upload_pdbs.sh" "${{ inputs.search-root }}"
